image: docker:latest

stages:
  - build

build:
  stage: build
  services:
    - docker:dind
  script:
    - echo "$CI_REGISTRY_USER"
    - echo "$CI_REGISTRY_PASSWORD"
    # - docker build -t "$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG" .
    # - docker push "$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG"
